### ISSUE TITLE
Undefined function FastRoute

### ISSUE THREAD

**Issue by duke-moose** [bobbyahines/DiscWolf#2]
**Fatal error**: Uncaught Error: Call to undefined function FastRoute\simpleDispatcher() in /var/www/html/public/index.php:8 Stack trace: #0 {main} thrown in /var/www/html/public/index.php on line 8

**Comment by duke-moose** [comment]
Solved with following:

```
docker run --rm --interactive --tty   --volume $PWD:/app   composer require nikic/fast-route
```

**Comment by bobbyahines** [comment]
This should be resolved by using the current Dockerfile-dev build via docker-compose.yml.
