### ISSUE TITLE
Error - 'Twig\Loader\FilesystemLoader'

### ISSUE THREAD

**Issue by duke-moose** [bobbyahines/DiscWolf#3]
**Fatal error**: Uncaught Error: Class 'Twig\Loader\FilesystemLoader' not found in /var/www/html/app/Controllers/Controller.php:16 Stack trace: #0 /var/www/html/public/index.php(38): DiscWolf\Controllers\Controller->__construct() #1 {main} thrown in /var/www/html/app/Controllers/Controller.php on line 16

**Comment by duke-moose** [comment]
Fixed with, but not programmatic:

```
docker run --rm --interactive --tty   --volume $PWD:/app   composer require "twig/twig:^3.0"
```

**Comment by bobbyahines** [comment]
This should be resolved by using the current Dockerfile-dev build via docker-compose.yml.
