### ISSUE TITLE
Page /startGame Permission Error

### ISSUE THREAD

**Issue by duke-moose** [bobbyahines/DiscWolf#5]
Permission error saving file. Since no file is saved no pages after /startGame function properly. Checked container directory user permission for /gameFiles is set to rxw for root, but main user set to user:group 1000:1000. Only read is supplied to this user. Likely need to update user permissions somehow.

Warning: file_put_contents(/var/www/html/public/gameFiles/b6c7560e-74ac-43c7-a542-b6e2ea8eab44.json): failed to open stream: Permission denied in /var/www/html/app/Utils/GameState.php on line 77
GameState::saveGame() -- Failed to save game file.

**Comment by bobbyahines** [comment]
This is a matter of conflict between the local directory being volumed into the docker container and the users in the container. In our container, the primary user is `www-data`, and the primary group is `www-data`, but you always get entered into the container as root. That `www-data` user (owned by Apache) needs write permissions to the `public/gameFiles` folder. To fix this in development, run a chown on the directory inside the container:  

`docker exec -it discwolf_app chown -R www-data:www-data public/gameFiles`.
